### PR TITLE
Update tests to use hazelcast-remote-controller

### PR DESCRIPTION
**Pull request by cangencer**

### CODE REVIEW

**Comment by cangencer** [comment]
verify

**Comment by cangencer** [comment]
verify

**Comment by hasancelik** [comment]
verify

**Comment by cangencer** [comment]
verify

**Comment by cangencer** [comment]
verify

**Comment by cangencer** [comment]
verify

**Comment by hasancelik** [comment]
verify

**Comment by hasancelik** [comment]
verify

**Pull request closed without merging**
