### PR TITLE
[API-274] SQL types

### PR DESCRIPTION
**Pull request by alexb5dh**

### CODE REVIEW

**Comment by zpqrtbnk** [comment]
Only 1 comment / question really: are the new types pure-SQL types, or could they be useful for other applications, and then, should they be in a `Hazelcast.Sql` namespace or in a less SQL namespace or even in the root namespace? What I mean is... SQL is a query language, these types could be used without using SQL, couln't they?

**Comment by mdumandag** [comment]
@zpqrtbnk In the Java client, these types (date types + BigDecimal) are used in

- SQL as return types/parameters of queries
- Portable as return types/parameters of readXXX/writeXXX methods
- new Compact Serialization as return types/parameters of readXXX/writeXXX methods

Also, they have default serializers registered for them (in 5.0), so they can also be used in any other data structure

**Comment by zpqrtbnk** [comment]
Suggesting we move them to `Hazelcast.Models` which contains various "models" such as the `MemberInfo` class.
WDYT?

**Comment by alexb5dh** [comment]
@zpqrtbnk @mdumandag 

Moved new types from `Hazelcast.Sql` to `Hazelcast.Models`. 
Corresponding tests file moved and renamed as: `/Sql/SqlDataTypesTests.cs` -> `Models/HazelcastDataTypesTests.cs`

**Review by zpqrtbnk — APPROVED** [review]
Looks good with the changes. Approved.

**Pull request merged**
