### PR TITLE
Switched to AsyncKeyedLock

### PR DESCRIPTION
**Pull request by MarkCiliaVincenti**
This PR reduces memory allocations

### CODE REVIEW

**Comment by emreyigit** [comment]
Hey @MarkCiliaVincenti, thank you for your contributions ❤️. We'll review the PR.

**Comment by MarkCiliaVincenti** [comment]
> Hey @MarkCiliaVincenti, thank you for your contributions ❤️. We'll review the PR.

Looking forward to this @emreyigit

**Comment by emreyigit** [comment]
Hey @MarkCiliaVincenti, thank you for your contribution. However, we have strict policy not to depend on 3rd party libraries. If there is any update about the policy, I'll update here.

**Comment by MarkCiliaVincenti** [comment]
That's unfortunate because this offered value to your project, but I understand.

**Pull request closed without merging**
