### PR TITLE
Update build script

### PR DESCRIPTION
**Pull request by zpqrtbnk**
Updates the build script, support code signing, cleanup how things work.

**NOTE: this renames the build script, and therefore requires that the jenkins tasks be updated.**

### CODE REVIEW

**Comment by zpqrtbnk** [comment]
verify

**Review by asimarslan — APPROVED** [review]

**Comment by zpqrtbnk** [comment]
verify

**Comment by zpqrtbnk** [comment]
verify

**Comment by zpqrtbnk** [comment]
verify

**Comment by zpqrtbnk** [comment]
verify

**Pull request merged**
