### PR TITLE
v4 architecture refactoring

### PR DESCRIPTION
**Pull request by zpqrtbnk**
This is the draft PR for the complete v4 architecture refactoring.

### CODE REVIEW

**Comment by zpqrtbnk** [comment]
verify

**Comment by zpqrtbnk** [comment]
verify

**Comment by zpqrtbnk** [comment]
verify

**Comment by zpqrtbnk** [comment]
verify

**Review by asimarslan — APPROVED** [review]
Great work @zpqrtbnk🥇 🥇 🥇 
Thanks for rewriting the client from scratch 🥇

**Pull request merged**
