### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Menighin**
Fix typo

### CODE REVIEW

**Comment by Scooletz** [comment]
Hey @Menighin . Thanks for noticing! 
I know it's a small fix, but first I'd like you to add yourself to our https://hazelcast.atlassian.net/wiki/spaces/COM/pages/6357071/Hazelcast+Contributor+Agreement
Could you do it?

**Comment by Menighin** [comment]
Hi @Scooletz , sure. 
But the only way is to download, print, hand sign, scan and email back? Isn't there a digital way of doing it? Lets save some paper :s

**Comment by Scooletz** [comment]
AFAIK we don't have an alternative CLA path right now. What you could do though is to use PDF fill&sign to not print it physically. I'll ask about potential CLA improvements in the background.

**Comment by Menighin** [comment]
Hi @Scooletz I signed in PDF and emailed it.
Thx

**Comment by Scooletz** [comment]
verify

**Comment by Scooletz** [comment]
Thank you @Menighin 🤗

**Pull request merged**
