### PR TITLE
thrift version upgrade

### PR DESCRIPTION
**Pull request by asimarslan**
* thrift version upgrade
* ConnectionManager bug fix

### CODE REVIEW

**Comment by zpqrtbnk** [comment]
Reviewing - any idea why the checks fail?

**Comment by zpqrtbnk** [comment]
Tests fail on my machine, because the following method in `ThreadSafeRemoteController` is infinitely recursive and ends up causing a `StackOverflowException`?

```
public Cluster createCluster(string hzVersion, string xmlconfig)
{
    return ThreadSafeCall(() => createCluster(hzVersion, xmlconfig));
}
```
In fact, most methods in this class seem to expose the same problem?

**Comment by asimarslan** [comment]
verify

**Comment by asimarslan** [comment]
verify

**Comment by asimarslan** [comment]
verify

**Comment by asimarslan** [comment]
verify

**Comment by asimarslan** [comment]
verify

**Pull request merged**
