### PR TITLE
Provide compact examples (same as Java) [API-978]

### PR DESCRIPTION
**Pull request by zpqrtbnk**
Provides the same code examples as Java does [here](https://github.com/hazelcast/hazelcast-code-samples/tree/master/serialization/compact/src/main/java). Simple but considered enough.

Remember: to run examples, start a server with `./hz.ps1 run-server` and then in another console, `./hz.ps1 run-example Serialization.CompactSerializationZeroConfigExample` will run the example.

### CODE REVIEW

**Comment by zpqrtbnk** [comment]
Sure could. But we decided with Metin to keep it super simple and in line with Java, which only has very minimal examples for now.

**Comment by srknzl** [comment]
@zpqrtbnk and @emreyigit FYI, these usages of `\` [here](https://github.com/hazelcast/hazelcast-csharp-client/blob/2cbe9bfc50a747bf2c40a4ed20653ec7af220b35/hz.ps1#L791)  are not portable and does not work on linux.

**Comment by srknzl** [comment]
I got an exception like

```
Exception in thread "main" com.hazelcast.core.HazelcastException: Config file at '/var/git/forked/hazelcast-csharp-client/temp/lib\hazelcast-5.1.xml' doesn't exist.
        at com.hazelcast.internal.config.AbstractConfigLocator.loadSystemPropertyFileResource(AbstractConfigLocator.java:274)
        at com.hazelcast.internal.config.AbstractConfigLocator.loadFromSystemProperty(AbstractConfigLocator.java:257)
        at com.hazelcast.internal.config.AbstractConfigLocator.loadFromSystemProperty(AbstractConfigLocator.java:224)
        at com.hazelcast.internal.config.XmlConfigLocator.locateFromSystemProperty(XmlConfigLocator.java:37)
        at com.hazelcast.config.Config.loadFromFile(Config.java:271)
        at com.hazelcast.config.Config.load(Config.java:240)
        at com.hazelcast.instance.impl.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:131)
        at com.hazelcast.core.Hazelcast.newHazelcastInstance(Hazelcast.java:95)
        at com.hazelcast.core.server.HazelcastMemberStarter.main(HazelcastMemberStarter.java:45)

```

while trying to start the server.

**Comment by srknzl** [comment]
Additional feedback: 

My powershell version was 7.1.7 or something like that and when I run ./hz.ps1 on windows I got:

image


I think my version was not old. Also the error message is strange.

**Pull request merged**
